const hotel1 = "https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel2 = "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel3 = "https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel4 = "https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel5 = "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel6 = "https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel7 = "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel8 = "https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel9 = "https://images.pexels.com/photos/1838554/pexels-photo-1838554.jpeg?auto=compress&cs=tinysrgb&w=800";
const hotel10 = "https://images.pexels.com/photos/3155666/pexels-photo-3155666.jpeg?auto=compress&cs=tinysrgb&w=800";

export const hotels= [
  {
    id: 1,
    name: "The Oberoi Cecil, Shimla",
    location: "Chaura Maidan, Shimla",
    area: "Mall Road Area",
    rating: 5,
    price: 16500,
    image: hotel1,
    images: [hotel1, hotel2, hotel3],
    description:
      "The Oberoi Cecil is one of Shimla's oldest heritage hotels, offering luxury rooms, heated indoor pool, spa, fine dining and stunning views of the mountains. It combines colonial charm with modern luxury.",
    amenities: [
      "Free WiFi",
      "Heated Pool",
      "Breakfast Included",
      "Spa",
      "Gym",
      "Mountain View",
      "Restaurant",
      "Bar",
      "Room Service",
      "Parking",
    ],
    reviews: [
      {
        id: 1,
        author: "Rajesh Kumar",
        rating: 5,
        date: "2024-01-15",
        comment: "Absolutely stunning property! The heritage charm combined with modern amenities makes it perfect. Staff was exceptional.",
        helpful: 24,
      },
      {
        id: 2,
        author: "Priya Sharma",
        rating: 5,
        date: "2024-01-10",
        comment: "Best hotel in Shimla. The heated pool and spa are amazing. Highly recommend for a luxurious stay.",
        helpful: 18,
      },
    ],
    totalReviews: 156,
    popular: true,
    roomTypes: [
      { type: "Deluxe Room", price: 16500, features: ["King Bed", "Mountain View", "Balcony"] },
      { type: "Premium Suite", price: 24000, features: ["King Bed", "Living Room", "Jacuzzi", "Valley View"] },
      { type: "Heritage Suite", price: 32000, features: ["Colonial Decor", "Separate Living Area", "Butler Service"] },
    ],
    nearby: ["Mall Road - 2 km", "Jakhu Temple - 3 km", "Ridge - 2.5 km", "Christ Church - 2.8 km"],
  },
  {
    id: 2,
    name: "Wildflower Hall, Mashobra",
    location: "Mashobra, Shimla",
    area: "Mashobra",
    rating: 5,
    price: 21000,
    image: hotel2,
    images: [hotel2, hotel1, hotel4],
    description:
      "Wildflower Hall is one of India's most luxurious mountain resorts. With breathtaking Himalayan views, infinity outdoor jacuzzi, spa therapies, and forest trails, it provides an unmatched royal experience.",
    amenities: ["Infinity Jacuzzi", "Mountain Trails", "Spa", "Free WiFi", "Fine Dining", "Gym", "Yoga Classes", "Library", "Bar", "24/7 Concierge"],
    reviews: [
      {
        id: 1,
        author: "Amit Patel",
        rating: 5,
        date: "2024-01-20",
        comment: "Paradise in the mountains! The views are breathtaking and the service is world-class. Perfect for a romantic getaway.",
        helpful: 32,
      },
    ],
    totalReviews: 203,
    deal: "20% OFF on 3+ nights",
    popular: true,
    roomTypes: [
      { type: "Deluxe Room", price: 21000, features: ["King Bed", "Himalayan View", "Fireplace"] },
      { type: "Premier Room", price: 28000, features: ["King Bed", "Private Balcony", "Valley View"] },
      { type: "Lord Kitchener Suite", price: 45000, features: ["Master Bedroom", "Living Room", "Private Terrace", "Butler"] },
    ],
    nearby: ["Craignano Nature Park - 5 km", "Mashobra Town - 1 km", "Shimla Town - 13 km"],
  },
  {
    id: 3,
    name: "Radisson Hotel Shimla",
    location: "Near Jakhu Temple Road",
    area: "Jakhu Hill",
    rating: 4,
    price: 9000,
    image: hotel3,
    images: [hotel3, hotel5, hotel6],
    description:
      "Radisson Shimla offers modern comfort with a rooftop pool, a multicuisine restaurant, and spacious rooms offering valley and city views. Popular for family vacations and business trips.",
    amenities: ["Rooftop Pool", "Free WiFi", "Restaurant", "Bar", "Valley View", "Gym", "Spa", "Parking", "Conference Room", "Kids Play Area"],
    reviews: [
      {
        id: 1,
        author: "Neha Singh",
        rating: 4,
        date: "2024-01-18",
        comment: "Great hotel with excellent facilities. The rooftop pool has amazing views. Good value for money.",
        helpful: 15,
      },
    ],
    totalReviews: 124,
    roomTypes: [
      { type: "Superior Room", price: 9000, features: ["Queen Bed", "City View"] },
      { type: "Deluxe Room", price: 12000, features: ["King Bed", "Valley View", "Mini Bar"] },
    ],
    nearby: ["Jakhu Temple - 1 km", "Mall Road - 2 km", "Scandal Point - 2.5 km"],
  },
  {
    id: 4,
    name: "Snow Valley Resorts",
    location: "Fingask Estate, Shimla",
    area: "Fingask",
    rating: 4,
    price: 7500,
    image: hotel4,
    images: [hotel4, hotel7, hotel8],
    description:
      "Affordable luxury resort with panoramic views of Shimla hills. Large rooms, rooftop dining, indoor games and nature-friendly interiors make it a great choice for families.",
    amenities: ["Free Parking", "Rooftop Dining", "Games Room", "WiFi", "Mountain View", "Restaurant", "Bonfire", "Garden"],
    reviews: [
      {
        id: 1,
        author: "Vikram Malhotra",
        rating: 4,
        date: "2024-01-12",
        comment: "Perfect for families! Kids loved the games room and the bonfire evening was memorable. Great value!",
        helpful: 22,
      },
    ],
    totalReviews: 89,
    deal: "Early Bird: 15% OFF",
    roomTypes: [
      { type: "Standard Room", price: 7500, features: ["Double Bed", "Garden View"] },
      { type: "Family Suite", price: 11000, features: ["2 Bedrooms", "Living Area", "Mountain View"] },
    ],
    nearby: ["Kufri - 8 km", "Mall Road - 5 km", "Green Valley - 3 km"],
  },
  {
    id: 5,
    name: "Hotel Willow Banks",
    location: "Mall Road, Shimla",
    area: "Mall Road Area",
    rating: 5,
    price: 12000,
    image: hotel5,
    images: [hotel5, hotel1, hotel9],
    description:
      "Located right on the famous Mall Road, Willow Banks offers colonial-style architecture, luxurious rooms, café, bar, salon, and a large terrace overlooking the hills.",
    amenities: ["Mall Road Access", "WiFi", "Salon", "Gym", "Restaurant", "Terrace View", "Bar", "Café", "Spa", "Library"],
    reviews: [
      {
        id: 1,
        author: "Kavita Reddy",
        rating: 5,
        date: "2024-01-22",
        comment: "Location is unbeatable! Right on Mall Road. The colonial architecture is beautiful and staff is very hospitable.",
        helpful: 28,
      },
    ],
    totalReviews: 167,
    popular: true,
    roomTypes: [
      { type: "Heritage Room", price: 12000, features: ["Colonial Decor", "Mall View"] },
      { type: "Premium Suite", price: 18000, features: ["Living Room", "Private Terrace", "Valley View"] },
    ],
    nearby: ["Mall Road - 0 km", "Ridge - 0.5 km", "Christ Church - 0.8 km", "Gaiety Theatre - 0.3 km"],
  },
  {
    id: 6,
    name: "Clarkes Hotel - A Heritage Grand Hotel",
    location: "The Mall, Shimla",
    area: "Mall Road Area",
    rating: 4,
    price: 8500,
    image: hotel6,
    images: [hotel6, hotel10, hotel2],
    description:
      "Clarkes Hotel is a refined heritage experience with vintage interiors, spacious suites, wooden architecture, and royal hospitality.",
    amenities: ["Vintage Rooms", "WiFi", "Restaurant", "Valley View", "Bar", "Heritage Tours", "Library", "Garden"],
    reviews: [
      {
        id: 1,
        author: "Rohit Kapoor",
        rating: 4,
        date: "2024-01-16",
        comment: "Beautiful heritage property with lots of history. Rooms are well-maintained and breakfast was delicious.",
        helpful: 19,
      },
    ],
    totalReviews: 98,
    roomTypes: [
      { type: "Classic Room", price: 8500, features: ["Vintage Decor", "Garden View"] },
      { type: "Heritage Suite", price: 14000, features: ["Period Furniture", "Living Area", "Valley View"] },
    ],
    nearby: ["Mall Road - 0.2 km", "Lakkar Bazaar - 1 km", "State Museum - 1.5 km"],
  },
  {
    id: 7,
    name: "Hotel Marina",
    location: "Mall Road",
    area: "Mall Road Area",
    rating: 4,
    price: 9500,
    image: hotel7,
    images: [hotel7, hotel3, hotel5],
    description:
      "A premium hotel on Mall Road with luxury rooms, spa services, terrace café, and exceptional city views. Ideal for honeymoon couples.",
    amenities: ["Spa", "WiFi", "Café", "Terrace", "City View", "Restaurant", "Room Service", "Honeymoon Packages"],
    reviews: [
      {
        id: 1,
        author: "Ananya & Karthik",
        rating: 5,
        date: "2024-01-19",
        comment: "Perfect for our honeymoon! The spa was relaxing and the terrace café has the best views. Very romantic!",
        helpful: 26,
      },
    ],
    totalReviews: 142,
    deal: "Honeymoon Special: Free Spa",
    roomTypes: [
      { type: "Deluxe Room", price: 9500, features: ["King Bed", "City View", "Mini Bar"] },
      { type: "Honeymoon Suite", price: 15000, features: ["King Bed", "Jacuzzi", "Terrace", "Complimentary Champagne"] },
    ],
    nearby: ["Mall Road - 0 km", "Scandal Point - 0.4 km", "Ridge - 0.6 km"],
  },
  {
    id: 8,
    name: "The Zion Hotel",
    location: "Shoghi, Shimla",
    area: "Shoghi",
    rating: 4,
    price: 6800,
    image: hotel8,
    images: [hotel8, hotel4, hotel6],
    description:
      "The Zion offers modern luxury with green landscapes, a peaceful environment, and great food. Great for nature lovers.",
    amenities: ["Green View", "WiFi", "Parking", "Restaurant", "Garden", "Nature Walks", "Bonfire", "Organic Food"],
    reviews: [
      {
        id: 1,
        author: "Meera Joshi",
        rating: 4,
        date: "2024-01-14",
        comment: "Peaceful and surrounded by nature. The organic food was fresh and delicious. Perfect for a quiet retreat.",
        helpful: 17,
      },
    ],
    totalReviews: 76,
    roomTypes: [
      { type: "Standard Room", price: 6800, features: ["Queen Bed", "Forest View"] },
      { type: "Premium Cottage", price: 10000, features: ["Private Cottage", "Garden", "Bonfire Pit"] },
    ],
    nearby: ["Shoghi Market - 2 km", "Tara Devi Temple - 5 km", "Shimla - 13 km"],
  },
  {
    id: 9,
    name: "The Royal Retreat",
    location: "Chharabra, Shimla",
    area: "Chharabra",
    rating: 5,
    price: 18000,
    image: hotel9,
    images: [hotel9, hotel1, hotel2],
    description:
      "A grand upscale property with modern amenities, luxury rooms, and spectacular panoramic views of the Himalayan mountains.",
    amenities: ["Luxury Suites", "Spa", "Jacuzzi", "Mountain View", "Fine Dining", "WiFi", "Gym", "Butler Service", "Helipad", "Conference Hall"],
    reviews: [
      {
        id: 1,
        author: "Arjun Mehta",
        rating: 5,
        date: "2024-01-21",
        comment: "Truly royal experience! The views are spectacular and the service is impeccable. Worth every penny.",
        helpful: 31,
      },
    ],
    totalReviews: 134,
    popular: true,
    roomTypes: [
      { type: "Royal Room", price: 18000, features: ["King Bed", "Mountain View", "Balcony"] },
      { type: "Presidential Suite", price: 35000, features: ["2 Bedrooms", "Living Room", "Private Jacuzzi", "Butler Service"] },
    ],
    nearby: ["Kufri - 5 km", "Fagu - 8 km", "Wildflower Hall - 7 km"],
  },
  {
    id: 10,
    name: "Hotel Landmark",
    location: "Near Sanjauli, Shimla",
    area: "Sanjauli",
    rating: 3,
    price: 5500,
    image: hotel10,
    images: [hotel10, hotel8, hotel4],
    description:
      "A budget-friendly property with clean rooms, balcony views, and easy accessibility to major landmarks.",
    amenities: ["WiFi", "Parking", "Balcony", "Restaurant", "Room Service"],
    reviews: [
      {
        id: 1,
        author: "Suresh Yadav",
        rating: 3,
        date: "2024-01-11",
        comment: "Good budget option. Rooms are clean and staff is friendly. Location could be better but decent for the price.",
        helpful: 12,
      },
    ],
    totalReviews: 54,
    deal: "Budget Deal: ₹4999/night",
    roomTypes: [
      { type: "Standard Room", price: 5500, features: ["Double Bed", "Balcony"] },
    ],
    nearby: ["Sanjauli Market - 0.5 km", "Mall Road - 4 km", "Bus Stand - 3 km"],
  },
  {
    id: 11,
    name: "The Cedar Grand Hotel & Spa",
    location: "Kufri Road, Shimla",
    area: "Kufri",
    rating: 5,
    price: 14500,
    image: hotel1,
    images: [hotel1, hotel5, hotel9],
    description:
      "Luxurious mountain retreat featuring world-class spa facilities, gourmet dining, and breathtaking snow-capped mountain views. Perfect blend of comfort and elegance.",
    amenities: ["World-Class Spa", "Heated Pool", "Fine Dining", "WiFi", "Mountain View", "Gym", "Yoga Studio", "Bar", "Valet Parking", "Kids Club"],
    reviews: [
      {
        id: 1,
        author: "Divya Nair",
        rating: 5,
        date: "2024-01-17",
        comment: "The spa is incredible! Best massage I've ever had. The mountain views from the room are stunning.",
        helpful: 21,
      },
    ],
    totalReviews: 118,
    popular: true,
    deal: "Spa Package: 25% OFF",
    roomTypes: [
      { type: "Deluxe Mountain View", price: 14500, features: ["King Bed", "Mountain View", "Bathtub"] },
      { type: "Cedar Suite", price: 22000, features: ["Living Room", "Private Balcony", "Jacuzzi", "Butler Service"] },
    ],
    nearby: ["Kufri - 3 km", "Mahasu Peak - 5 km", "Himalayan Nature Park - 4 km"],
  },
  {
    id: 12,
    name: "Summit Le Royale Hotel",
    location: "Bharari, Shimla",
    area: "Bharari",
    rating: 4,
    price: 8900,
    image: hotel2,
    images: [hotel2, hotel6, hotel10],
    description:
      "Contemporary hotel with modern amenities, multi-cuisine restaurant, and stunning valley views. Ideal for business and leisure travelers.",
    amenities: ["Restaurant", "Bar", "WiFi", "Valley View", "Gym", "Conference Room", "Parking", "Room Service", "Travel Desk"],
    reviews: [
      {
        id: 1,
        author: "Rahul Saxena",
        rating: 4,
        date: "2024-01-13",
        comment: "Good hotel for business trips. The conference facilities are excellent and staff is professional.",
        helpful: 14,
      },
    ],
    totalReviews: 92,
    roomTypes: [
      { type: "Executive Room", price: 8900, features: ["King Bed", "Work Desk", "Valley View"] },
      { type: "Business Suite", price: 13500, features: ["Meeting Area", "Executive Lounge Access", "Mini Bar"] },
    ],
    nearby: ["Bharari Market - 1 km", "Mall Road - 3.5 km", "Annandale - 6 km"],
  },
  {
    id: 13,
    name: "Hotel Combermere",
    location: "The Mall, Shimla",
    area: "Mall Road Area",
    rating: 4,
    price: 10500,
    image: hotel3,
    images: [hotel3, hotel7, hotel1],
    description:
      "Historic hotel on Mall Road with colonial architecture, elegant rooms, and traditional hospitality. Features period furniture and modern comforts.",
    amenities: ["Mall Road Location", "WiFi", "Heritage Building", "Restaurant", "Bar", "Terrace", "Library", "Room Service"],
    reviews: [
      {
        id: 1,
        author: "Sanjay Gupta",
        rating: 4,
        date: "2024-01-20",
        comment: "Beautiful colonial property with lots of character. The location on Mall Road is perfect for shopping and sightseeing.",
        helpful: 18,
      },
    ],
    totalReviews: 105,
    roomTypes: [
      { type: "Heritage Room", price: 10500, features: ["Period Furniture", "Mall View"] },
      { type: "Colonial Suite", price: 16000, features: ["Living Area", "Antique Decor", "Terrace"] },
    ],
    nearby: ["Mall Road - 0 km", "Lower Bazaar - 0.5 km", "Kali Bari Temple - 1 km"],
  },
  {
    id: 14,
    name: "Apple Blossom Resort",
    location: "Fagu, Shimla",
    area: "Fagu",
    rating: 4,
    price: 7200,
    image: hotel4,
    images: [hotel4, hotel8, hotel3],
    description:
      "Charming resort nestled in apple orchards with cozy cottages, organic farm-to-table dining, and peaceful mountain ambiance.",
    amenities: ["Organic Food", "Apple Orchard", "Bonfire", "WiFi", "Parking", "Nature Walks", "Garden", "Restaurant"],
    reviews: [
      {
        id: 1,
        author: "Pooja Agarwal",
        rating: 4,
        date: "2024-01-15",
        comment: "Loved the orchard setting! Fresh air, peaceful environment, and the organic food was amazing. Great for families.",
        helpful: 20,
      },
    ],
    totalReviews: 68,
    deal: "Weekend Getaway: 18% OFF",
    roomTypes: [
      { type: "Cottage Room", price: 7200, features: ["Orchard View", "Cozy Interiors"] },
      { type: "Family Cottage", price: 11000, features: ["2 Bedrooms", "Private Garden", "Kitchen"] },
    ],
    nearby: ["Fagu Village - 1 km", "Kufri - 6 km", "Theog - 15 km"],
  },
  {
    id: 15,
    name: "The Himalayan Retreat",
    location: "Summer Hill, Shimla",
    area: "Summer Hill",
    rating: 4,
    price: 9800,
    image: hotel5,
    images: [hotel5, hotel2, hotel9],
    description:
      "Serene property in the quiet Summer Hill area offering panoramic valley views, spacious rooms, and personalized service.",
    amenities: ["Valley View", "WiFi", "Restaurant", "Garden", "Bonfire", "Parking", "Library", "Meditation Area"],
    reviews: [
      {
        id: 1,
        author: "Manish Verma",
        rating: 4,
        date: "2024-01-18",
        comment: "Very peaceful location away from the tourist crowds. Great for relaxation and the views are phenomenal.",
        helpful: 16,
      },
    ],
    totalReviews: 81,
    roomTypes: [
      { type: "Valley View Room", price: 9800, features: ["Queen Bed", "Valley View", "Balcony"] },
      { type: "Retreat Suite", price: 15000, features: ["King Bed", "Living Area", "Private Terrace"] },
    ],
    nearby: ["Summer Hill Market - 0.5 km", "Himachal University - 2 km", "Mall Road - 5 km"],
  },
  {
    id: 16,
    name: "Pine Grove Resort",
    location: "Mashobra Road, Shimla",
    area: "Mashobra",
    rating: 3,
    price: 6200,
    image: hotel6,
    images: [hotel6, hotel4, hotel7],
    description:
      "Budget-friendly resort surrounded by pine forests, offering comfortable rooms, local cuisine, and adventure activities.",
    amenities: ["Forest View", "WiFi", "Restaurant", "Parking", "Trekking", "Bonfire", "Garden"],
    reviews: [
      {
        id: 1,
        author: "Ravi Kumar",
        rating: 3,
        date: "2024-01-12",
        comment: "Good budget option if you want to stay close to nature. Rooms are basic but clean. The trekking tours were fun.",
        helpful: 11,
      },
    ],
    totalReviews: 47,
    roomTypes: [
      { type: "Standard Room", price: 6200, features: ["Double Bed", "Forest View"] },
    ],
    nearby: ["Mashobra - 2 km", "Craignano - 4 km", "Reserve Forest Sanctuary - 3 km"],
  },
  {
    id: 17,
    name: "Grand Sunset Hotel",
    location: "Circular Road, Shimla",
    area: "Circular Road",
    rating: 4,
    price: 8200,
    image: hotel7,
    images: [hotel7, hotel5, hotel10],
    description:
      "Modern hotel with spectacular sunset views, rooftop restaurant, and convenient location near major attractions.",
    amenities: ["Rooftop Restaurant", "Sunset View", "WiFi", "Bar", "Parking", "Room Service", "Travel Assistance"],
    reviews: [
      {
        id: 1,
        author: "Sneha Iyer",
        rating: 4,
        date: "2024-01-16",
        comment: "The sunset views from the rooftop are absolutely gorgeous! Great food and friendly staff.",
        helpful: 23,
      },
    ],
    totalReviews: 96,
    roomTypes: [
      { type: "Sunset View Room", price: 8200, features: ["Queen Bed", "Sunset View", "Balcony"] },
      { type: "Premium Suite", price: 12500, features: ["King Bed", "Living Area", "Panoramic View"] },
    ],
    nearby: ["Mall Road - 1.5 km", "Ridge - 1.8 km", "Scandal Point - 2 km"],
  },
  {
    id: 18,
    name: "Mountain Mist Boutique Hotel",
    location: "Kaithu, Shimla",
    area: "Kaithu",
    rating: 4,
    price: 7800,
    image: hotel8,
    images: [hotel8, hotel1, hotel6],
    description:
      "Boutique property with artistically designed rooms, personalized service, and authentic local experiences.",
    amenities: ["Boutique Rooms", "WiFi", "Café", "Art Gallery", "Local Tours", "Garden", "Library"],
    reviews: [
      {
        id: 1,
        author: "Aisha Khan",
        rating: 4,
        date: "2024-01-14",
        comment: "Unique and charming hotel! Each room is beautifully decorated. The local tour arranged by hotel was excellent.",
        helpful: 19,
      },
    ],
    totalReviews: 73,
    deal: "Art Lovers Special",
    roomTypes: [
      { type: "Artist Room", price: 7800, features: ["Themed Decor", "Local Art", "Garden View"] },
      { type: "Gallery Suite", price: 12000, features: ["Curated Art", "Private Balcony", "Living Area"] },
    ],
    nearby: ["Kaithu Market - 0.8 km", "Sankat Mochan Temple - 2 km", "Mall Road - 2.5 km"],
  },
  {
    id: 19,
    name: "Alpine Meadows Lodge",
    location: "Kufri Heights",
    area: "Kufri",
    rating: 4,
    price: 8600,
    image: hotel9,
    images: [hotel9, hotel4, hotel2],
    description:
      "Mountain lodge with adventure activities, cozy fireplaces, and easy access to skiing and trekking trails.",
    amenities: ["Fireplace", "Adventure Sports", "WiFi", "Restaurant", "Ski Equipment", "Trekking Guides", "Bonfire"],
    reviews: [
      {
        id: 1,
        author: "Karan Thakur",
        rating: 4,
        date: "2024-01-19",
        comment: "Perfect for adventure enthusiasts! Skiing was amazing and the fireplace in the room was so cozy after a day outdoors.",
        helpful: 25,
      },
    ],
    totalReviews: 87,
    popular: true,
    roomTypes: [
      { type: "Lodge Room", price: 8600, features: ["Fireplace", "Mountain View"] },
      { type: "Adventure Suite", price: 13000, features: ["Living Area", "Private Fireplace", "Ski Storage"] },
    ],
    nearby: ["Kufri Fun World - 1 km", "Mahasu Peak - 2 km", "Skiing Slopes - 0.5 km"],
  },
  {
    id: 20,
    name: "Valley View Homestay",
    location: "Totu, Shimla",
    area: "Totu",
    rating: 3,
    price: 4500,
    image: hotel10,
    images: [hotel10, hotel6, hotel8],
    description:
      "Authentic homestay experience with home-cooked meals, warm hospitality, and stunning valley views. Perfect for budget travelers seeking local culture.",
    amenities: ["Home-Cooked Meals", "Valley View", "WiFi", "Garden", "Local Experience", "Parking"],
    reviews: [
      {
        id: 1,
        author: "Nisha Gupta",
        rating: 3,
        date: "2024-01-10",
        comment: "Great homestay for authentic experience. The hosts were wonderful and the food was delicious. Very economical!",
        helpful: 13,
      },
    ],
    totalReviews: 42,
    deal: "Long Stay: 20% OFF on 5+ nights",
    roomTypes: [
      { type: "Homestay Room", price: 4500, features: ["Local Experience", "Home-cooked Food", "Valley View"] },
    ],
    nearby: ["Totu Village - 0.2 km", "Mall Road - 6 km", "Local Market - 0.5 km"],
  },
];

export const locations = ["All Areas", "Mall Road Area", "Mashobra", "Jakhu Hill", "Kufri", "Fagu", "Chharabra", "Sanjauli", "Shoghi", "Summer Hill", "Bharari", "Circular Road", "Kaithu", "Fingask", "Totu"];

export const allAmenities = [
  "Free WiFi",
  "Spa",
  "Gym",
  "Swimming Pool",
  "Restaurant",
  "Bar",
  "Parking",
  "Mountain View",
  "Room Service",
  "Breakfast Included",
  "Pet Friendly",
  "Airport Shuttle",
];
